### ISSUE TITLE
Other potential docs components

### ISSUE THREAD

**Issue by colleenmcginnis** [mapbox/frontend-documentation#16]
I think we have issues open for all the components that we need to make sure that the structure of pages across repos are consistent. We could also consider adding components for: 

- Components that determine the layout of the content in the wider column in `PageLayout`, like:
  - [`OverviewGuide`](https://github.com/mapbox/android-docs/blob/mb-pages/src/components/overview-guide.js)
  - [`ExamplePageLayout`](https://github.com/mapbox/android-docs/blob/mb-pages/src/components/examples-page.js)
  - [`HelpPageLayout`](https://github.com/mapbox/android-docs/blob/mb-pages/src/components/help-page.js)
- Components that are used in Markdown files, like:
  - `CodeLanguageToggle`
  - `ToggleableCodeBlock`
  - `SideBySideComparison`

@danswick @davidtheclark do we want to work on those in this initial push? ☝️

**Comment by davidtheclark** [comment]
@colleenmcginnis I think you can make the call based on how much you want to invest in the initial push, especially if a choice would open or block work that you want to do (e.g. work on Help). I can see reasons for doing more at once, but also reasons for making a first move soon and adding to it later.

**Comment by colleenmcginnis** [comment]
Ok I opened issues for everything that I think we should finish in this initial push.
